### ISSUE TITLE
Panic on too large requests

### ISSUE THREAD

**Issue by tomtau** [tendermint/rust-abci#28]
https://github.com/tendermint/rust-abci/blob/master/src/server.rs#L99

As mentioned here: https://github.com/tendermint/rust-abci/pull/21#issuecomment-443080088

**Comment by davebryson** [comment]
@tomtau  I think this can be closed now right?

**Comment by tomtau** [comment]
Yes, I think this can be closed once https://github.com/tendermint/rust-abci/pull/34 is merged

**Comment by davebryson** [comment]
@zramsay This can be closed as well when #34 is merged
