### ISSUE TITLE
ResponseQuery type doesn't capture the 0.26 change

### ISSUE THREAD

**Issue by tomtau** [tendermint/rust-abci#33]
It should have the merkle proof as in: https://github.com/davebryson/rust-abci/blob/da_protobufs/abci-protobuf/src/abci.rs#L5571

**Comment by davebryson** [comment]
I'll be adding a pull request with a new subpackage for building protobufs along with some other changes in the next few days.

**Comment by tomtau** [comment]
@davebryson awesome! Just one minor pre-PR comment: consider re-exporting (`pub use`) some main things, such as Request/Response types, from the `abci_protobuf` sub package, so that one doesn't need to always include two crates and import from two places on the client side.

**Comment by davebryson** [comment]
@tomtau I like the idea, but how far do you go with it?   You can re-export `abci` so clients can simple call `use abci::ResponseInfo`, etc...  But what about `KVPairs` in `types` and `merkle`?   Should they also be re-exported?  This could get a bit confusing.  Additionally `KVPairs` mod `types` should be aliased as I'll bet someone would end up with another `types` mod in their code.

I've actually been pondering the whole value of the protobufs stuff living in a separate crate.  Should it really be there or simply part of a submodule?  Is there any real value for the protobuf message code to live in it's own crate?

**Comment by davebryson** [comment]
@zramsay pull #34 should address this issue. So you should be able to close it if you like.
