### ISSUE TITLE
Setup dependabot

### ISSUE THREAD

**Issue by tomtau** [tendermint/rust-abci#64]
It supports Rust.
I guess it'll make sense after https://github.com/tendermint/rust-abci/issues/63

**Comment by marbar3778** [comment]
this is enabled, but since on some of the versions we don't specify the last version number, depndabot ignores minor releases and goes for changes that occur on `X.X`. Do we want to add `X.X.x` so depndabot can update minor releases as well?

**Comment by tomtau** [comment]
I think that would make sense with https://github.com/tendermint/rust-abci/issues/70 if there's a separate crate and Cargo.lock for examples

**Comment by tomtau** [comment]
@marbar3778 adding minor releases may be desirable -- see https://github.com/tendermint/rust-abci/issues/87

**Comment by tomtau** [comment]
@marbar3778 are you sure it's set up? For `env_logger = "0.6.2"`, there was no PR for "0.7.0" opened yet

**Comment by tomtau** [comment]
seems ok now https://github.com/tendermint/rust-abci/pull/88
