### ISSUE TITLE
Outdated link in Cargo.toml

### ISSUE THREAD

**Issue by Liamsi** [tendermint/rust-abci#74]
## Summary of Bug

Link in crate gives 404:
https://github.com/tendermint/rust-abci/blob/587761552bbd0a25bacdc06c39fad17e5b35970b/Cargo.toml#L7

**Comment by Liamsi** [comment]
Instead could link to 
https://tendermint.com/docs/spec/abci/
https://tendermint.com/docs/app-dev/getting-started.html 
https://tendermint.com/docs/introduction/what-is-tendermint.html#abci-overview
https://tendermint.com/docs/app-dev/app-architecture.html
instead?

**Comment by tomtau** [comment]
fixed in https://github.com/tendermint/rust-abci/pull/81
