### ISSUE TITLE
Reduce amount of longs under `info`

### ISSUE THREAD

**Issue by marbar3778** [tendermint/rust-abci#78]
<img width="754" alt="Screen Shot 2019-06-27 at 6 25 35 PM" src="https://user-images.githubusercontent.com/24299864/60283270-16ee9280-9909-11e9-908c-852f96729fa7.png">

Make some of the logs outputted in the console when running the abci server log level debug.

@tomtau @Liamsi  how do you feel about this?

**Comment by tomtau** [comment]
agree, their log level could be changed

**Comment by tomtau** [comment]
fixed in https://github.com/tendermint/rust-abci/pull/80
